language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - PRETTYNAME="Bat Badge 2018"
    - ARDUINO_IDE_VERSION="1.8.5"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
#    - DOXYFILE: /home/travis/build/theDevilsVoice/NolaCon_2018/arduino/nola_con/Doxyfile

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/DEAD10C5/bat_mini/master/install.sh)
install:
  #- ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
  - arduino --install-library "APA102"
  #- arduino --install-library "Adafruit SleepyDog Library,Adafruit MQTT Library"

script:
  - build_main_platforms
  #- arduino --verify --board arduino:avr:uno $PWD/examples/FONAtest/FONAtest.ino
  #- arduino --verify --board arduino:avr:uno $PWD/examples/IncomingCall/IncomingCall.ino
  #- arduino --verify --board arduino:avr:uno $PWD/examples/AdafruitIO_GPS/AdafruitIO_GPS.ino
  - arduino --verify --board arduino:ATtiny:ATtiny $PWD/DEAD10C5/bat_mini/arduino/bat_mini_2018.ino
  - arduino --verify --board arduino:ATtiny:ATtiny $PWD/examples/APA102/Brightness.ino
notifications:
  email:
    on_success: change
    on_failure: change
