language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - PRETTYNAME="Bat Badge 2018"
    - ARDUINO_IDE_VERSION="1.8.6"
      # Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
#    - DOXYFILE: /home/travis/build/theDevilsVoice/NolaCon_2018/arduino/nola_con/Doxyfile

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/DEAD10C5/bat_mini/master/install.sh)
install:
  - arduino --install-library "APA102"

script:
  - arduino --verify --board attiny:avr:attiny:cpu=attiny84 /home/travis/DEAD10C5/bat_mini/arduino/bat_mini_2018.ino
  - build_platform attiny
 
notifications:
  email:
    on_success: change
    on_failure: change
